/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpRsaKey */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpRsaKey
#define _Included_com_amazon_corretto_crypto_provider_EvpRsaKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpRsaKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpRsaKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaKey_serialVersionUID 1LL
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpRsaKey
 * Method:    getModulus
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpRsaKey_getModulus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpRsaKey
 * Method:    getPublicExponent
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpRsaKey_getPublicExponent
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
