/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_SelfTestSuite */

#ifndef _Included_com_amazon_corretto_crypto_provider_SelfTestSuite
#define _Included_com_amazon_corretto_crypto_provider_SelfTestSuite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_corretto_crypto_provider_SelfTestSuite
 * Method:    awsLcSelfTestsPassed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_amazon_corretto_crypto_provider_SelfTestSuite_awsLcSelfTestsPassed
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
