/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_RsaGen */

#ifndef _Included_com_amazon_corretto_crypto_provider_RsaGen
#define _Included_com_amazon_corretto_crypto_provider_RsaGen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_corretto_crypto_provider_RsaGen
 * Method:    generateEvpKey
 * Signature: (IZ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_amazon_corretto_crypto_provider_RsaGen_generateEvpKey
  (JNIEnv *, jclass, jint, jboolean, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
