/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpEcPublicKey */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpEcPublicKey
#define _Included_com_amazon_corretto_crypto_provider_EvpEcPublicKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpEcPublicKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpEcPublicKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpEcPublicKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpEcPublicKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpEcPublicKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpEcPublicKey_serialVersionUID 1LL
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpEcPublicKey
 * Method:    getPublicPointCoords
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_EvpEcPublicKey_getPublicPointCoords
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
