/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpSignatureRaw */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpSignatureRaw
#define _Included_com_amazon_corretto_crypto_provider_EvpSignatureRaw
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpSignatureRaw_RSA_PKCS1_PADDING
#define com_amazon_corretto_crypto_provider_EvpSignatureRaw_RSA_PKCS1_PADDING 1L
#undef com_amazon_corretto_crypto_provider_EvpSignatureRaw_RSA_PKCS1_PSS_PADDING
#define com_amazon_corretto_crypto_provider_EvpSignatureRaw_RSA_PKCS1_PSS_PADDING 6L
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpSignatureRaw
 * Method:    signRaw
 * Signature: (JIJI[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpSignatureRaw_signRaw
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpSignatureRaw
 * Method:    verifyRaw
 * Signature: (JIJI[BII[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_amazon_corretto_crypto_provider_EvpSignatureRaw_verifyRaw
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
