/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_RsaCipher */

#ifndef _Included_com_amazon_corretto_crypto_provider_RsaCipher
#define _Included_com_amazon_corretto_crypto_provider_RsaCipher
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_RsaCipher_HANDLE_USAGE_IGNORE
#define com_amazon_corretto_crypto_provider_RsaCipher_HANDLE_USAGE_IGNORE 1L
#undef com_amazon_corretto_crypto_provider_RsaCipher_HANDLE_USAGE_USE
#define com_amazon_corretto_crypto_provider_RsaCipher_HANDLE_USAGE_USE 2L
#undef com_amazon_corretto_crypto_provider_RsaCipher_HANDLE_USAGE_CREATE
#define com_amazon_corretto_crypto_provider_RsaCipher_HANDLE_USAGE_CREATE 3L
/*
 * Class:     com_amazon_corretto_crypto_provider_RsaCipher
 * Method:    cipher
 * Signature: (JIIJJ[BII[BI)I
 */
JNIEXPORT jint JNICALL Java_com_amazon_corretto_crypto_provider_RsaCipher_cipher
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
