/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpSignatureBase */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpSignatureBase
#define _Included_com_amazon_corretto_crypto_provider_EvpSignatureBase
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpSignatureBase_RSA_PKCS1_PADDING
#define com_amazon_corretto_crypto_provider_EvpSignatureBase_RSA_PKCS1_PADDING 1L
#undef com_amazon_corretto_crypto_provider_EvpSignatureBase_RSA_PKCS1_PSS_PADDING
#define com_amazon_corretto_crypto_provider_EvpSignatureBase_RSA_PKCS1_PSS_PADDING 6L
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpSignatureBase
 * Method:    destroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_EvpSignatureBase_destroyContext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
