/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_LibCryptoRng */

#ifndef _Included_com_amazon_corretto_crypto_provider_LibCryptoRng
#define _Included_com_amazon_corretto_crypto_provider_LibCryptoRng
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_LibCryptoRng_serialVersionUID
#define com_amazon_corretto_crypto_provider_LibCryptoRng_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_LibCryptoRng_MAX_SINGLE_REQUEST
#define com_amazon_corretto_crypto_provider_LibCryptoRng_MAX_SINGLE_REQUEST 8192L
/*
 * Class:     com_amazon_corretto_crypto_provider_LibCryptoRng
 * Method:    generate
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_LibCryptoRng_generate
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
