/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_Loader */

#ifndef _Included_com_amazon_corretto_crypto_provider_Loader
#define _Included_com_amazon_corretto_crypto_provider_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_corretto_crypto_provider_Loader
 * Method:    getNativeLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_amazon_corretto_crypto_provider_Loader_getNativeLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_amazon_corretto_crypto_provider_Loader
 * Method:    validateLibcryptoVersion
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_amazon_corretto_crypto_provider_Loader_validateLibcryptoVersion
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_amazon_corretto_crypto_provider_Loader
 * Method:    isFipsMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_amazon_corretto_crypto_provider_Loader_isFipsMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
