/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi */

#ifndef _Included_com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi
#define _Included_com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA1_CODE
#define com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA1_CODE 1L
#undef com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA256_CODE
#define com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA256_CODE 2L
#undef com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA384_CODE
#define com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA384_CODE 3L
#undef com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA512_CODE
#define com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_SHA512_CODE 4L
/*
 * Class:     com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi
 * Method:    hkdf
 * Signature: ([BII[BI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_hkdf
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi
 * Method:    hkdfExtract
 * Signature: ([BII[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_hkdfExtract
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi
 * Method:    hkdfExpand
 * Signature: ([BII[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_HkdfSecretKeyFactorySpi_hkdfExpand
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
