/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpEcPrivateKey */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpEcPrivateKey
#define _Included_com_amazon_corretto_crypto_provider_EvpEcPrivateKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpEcPrivateKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpEcPrivateKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpEcPrivateKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpEcPrivateKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpEcPrivateKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpEcPrivateKey_serialVersionUID 1LL
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpEcPrivateKey
 * Method:    getPrivateValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpEcPrivateKey_getPrivateValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
