/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpKey */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpKey
#define _Included_com_amazon_corretto_crypto_provider_EvpKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpKey_serialVersionUID 1LL
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpKey
 * Method:    releaseKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_EvpKey_releaseKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpKey
 * Method:    encodePublicKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpKey_encodePublicKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpKey
 * Method:    encodePrivateKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpKey_encodePrivateKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpKey
 * Method:    getDerEncodedParams
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpKey_getDerEncodedParams
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
