/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EcGen */

#ifndef _Included_com_amazon_corretto_crypto_provider_EcGen
#define _Included_com_amazon_corretto_crypto_provider_EcGen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_corretto_crypto_provider_EcGen
 * Method:    buildEcParams
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_amazon_corretto_crypto_provider_EcGen_buildEcParams
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_amazon_corretto_crypto_provider_EcGen
 * Method:    freeEcParams
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_EcGen_freeEcParams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_corretto_crypto_provider_EcGen
 * Method:    generateEvpEcKey
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_amazon_corretto_crypto_provider_EcGen_generateEvpEcKey
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_amazon_corretto_crypto_provider_EcGen
 * Method:    generateEvpEcKeyFromSpec
 * Signature: ([BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_amazon_corretto_crypto_provider_EcGen_generateEvpEcKeyFromSpec
  (JNIEnv *, jclass, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
