/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey
#define _Included_com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_serialVersionUID 1LL
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey
 * Method:    getCrtParams
 * Signature: (J[B[B[B[B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_getCrtParams
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey
 * Method:    hasCrtParams
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_amazon_corretto_crypto_provider_EvpRsaPrivateCrtKey_hasCrtParams
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
