/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpRsaPrivateKey */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpRsaPrivateKey
#define _Included_com_amazon_corretto_crypto_provider_EvpRsaPrivateKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_serialVersionUID 1LL
#undef com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_serialVersionUID
#define com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_serialVersionUID 1LL
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpRsaPrivateKey
 * Method:    encodeRsaPrivateKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_encodeRsaPrivateKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_corretto_crypto_provider_EvpRsaPrivateKey
 * Method:    getPrivateExponent
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpRsaPrivateKey_getPrivateExponent
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
