/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpKeyAgreement */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpKeyAgreement
#define _Included_com_amazon_corretto_crypto_provider_EvpKeyAgreement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_corretto_crypto_provider_EvpKeyAgreement
 * Method:    agree
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_amazon_corretto_crypto_provider_EvpKeyAgreement_agree
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
