/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi */

#ifndef _Included_com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi
#define _Included_com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi
#ifdef __cplusplus
extern "C" {
#endif
#undef com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi_BLOCK_SIZE
#define com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi_BLOCK_SIZE 16L
/*
 * Class:     com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi
 * Method:    wrapKey
 * Signature: ([B[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi_wrapKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi
 * Method:    unwrapKey
 * Signature: ([B[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_amazon_corretto_crypto_provider_AesKeyWrapPaddingSpi_unwrapKey
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
