/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_corretto_crypto_provider_EvpMessageDigest */

#ifndef _Included_com_amazon_corretto_crypto_provider_EvpMessageDigest
#define _Included_com_amazon_corretto_crypto_provider_EvpMessageDigest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_corretto_crypto_provider_SHA256Spi
 * Method:    fastDigest
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_com_amazon_corretto_crypto_provider_EvpMessageDigest_singlePassDigest
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
